<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
Advance Operation With Business Examples
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [6]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])
print("=== Zomato Sales Analysis ===")
print("\n Sales data shape",sales_data.shape)
print("\n Sample data for first three restaurants: ",sales_data[0:3])
print("\n Sample data for first three restaurants without id: ",sales_data[0:3,1:])

=== Zomato Sales Analysis ===

 Sales data shape (5, 5)

 Sample data for first three restaurants:  [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

 Sample data for first three restaurants without id:  [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]]


<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
Total Sales per year
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [21]:
yearly_total=np.sum(sales_data[:,1:],axis=0)
print("yearly_total",yearly_total)

yearly_total [ 810000  945000 1085000 1240000]


<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
Minimum Sales per restaurant
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [22]:
minimum_sales_per_rest=np.min(sales_data[:,1:],axis=1)
print(minimum_sales_per_rest)

[150000 120000 200000 180000 160000]


<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
Maximum Sales per year
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [23]:
max_sales_per_year=np.max(sales_data[:,1:],axis=0)
print(max_sales_per_year)

[200000 230000 260000 300000]


<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
Average Sales per restaurant
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [24]:
avg_sales_per_rest=np.average(sales_data[:,1:],axis=1)
print(avg_sales_per_rest)

[200000. 152500. 247500. 225000. 195000.]


In [25]:
cumsum=np.cumsum(sales_data[:,1:],axis=1)
print(cumsum)


[[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]


In [28]:
vector1=np.array([1,2,3,4,5])
vector2=np.array([6,7,8,9,10])
print("vector addition ",vector1+vector2)
print("vector multiplication ",vector1*vector2)
print("Dot product ",np.dot(vector1,vector2))

vector addition  [ 7  9 11 13 15]
vector multiplication  [ 6 14 24 36 50]
Dot product  130


In [30]:
angle=np.arccos( np.dot(vector1,vector2)/(np.linalg.norm(vector1)*np.linalg.norm(vector2)))
print(angle)

0.26554161733900966


In [31]:
restaurant_types=np.array(['biryani','chinese','pizza','burger'])
vectorized_upper=np.vectorize(str.upper)
print(vectorized_upper(restaurant_types))

['BIRYANI' 'CHINESE' 'PIZZA' 'BURGER']


In [32]:
monthly_avg=sales_data[:,1:]/12
print(monthly_avg)

[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
