<h1 style="text-align: center; font-family: Georgia, serif; letter-spacing: 6px; color: #fff; font-size: 2.8em; font-weight: 900; margin-bottom: 0;">
  NUMPY
</h1>
<p style="text-align: center; color: #7f8c8d; letter-spacing: 3px; font-size: 0.85em; margin-top: 6px;">
  NUMERICAL PYTHON  •  DATA SCIENCE SERIES
</p>
<hr style="border: none; height: 2px; background-color: #2c3e50; width: 50%; margin: 10px auto;">

In [2]:
import numpy as np

In [ ]:
array_1d=np.array([1,2,3])
print(array_1d)

array_2d=np.array([[1 , 2, 3],[4, 5, 6]]) 
print(array_2d)

[1 2 3]
[[1 2 3]
 [4 5 6]]


<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
 List vs Numpy Array
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [ ]:
py_list=[1,2,3]
print("list",py_list*2)

np_array=np.array([1,2,3])# element wise multiplication
print("np_array",np_array*2)

list [1, 2, 3, 1, 2, 3]
np_array [2 4 6]


<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
  Creating Array from scratch
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [20]:
zeros=np.zeros((3,4))
print(zeros)


ones=np.ones((3,4))
print(ones)

full=np.full((2,2),7)
print("\n full",full)

random=np.random.random((2,4))
print("\n random",random)


sequence=np.arange(0,10,2)
print("\n sequence array",sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 full [[7 7]
 [7 7]]

 random [[0.71179781 0.83432667 0.15329815 0.20657296]
 [0.17677901 0.06637397 0.53362418 0.05211317]]

 sequence array [0 2 4 6 8]


<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
  Vector , Matrix and Tensor
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [3]:
vector=np.array([1,2,3])
print("Vector",vector)

matrix=np.array([[1,2,3],[4,5,6]])
print("Matrix",matrix)

tensor=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
print("tensor",tensor)

Vector [1 2 3]
Matrix [[1 2 3]
 [4 5 6]]
tensor [[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
  Array Properties
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [4]:
arr=np.array([[1,2,3],[4,5,6]])
print("array shape",arr.shape)
print("Dimension",arr.ndim)
print("Size",arr.size)
print("Dtype",arr.dtype)

array shape (2, 3)
Dimension 2
Size 6
Dtype int64


<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
  Array Reshaping
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [ ]:
arr=np.arange(12)
print("Original array ",arr)

reshaped=arr.reshape((3,4))
print("\n Reshaped array ",reshaped)

flattened=reshaped.flatten() # it gives copy instead of original array
print("\n Flattened array ",flattened)

raveled=reshaped.ravel()()# it gives original array instead of copy
print("\n Raveled array ",raveled)

Transpose=reshaped.T
print("\n Transposed array ",Transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
