<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
 Numpy Array Operations 
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [1]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing ",arr[2:7])
print("With step ",arr[1:8:2])
print("Negative indexing ",arr[-3])

Basic Slicing  [3 4 5 6 7]
With step  [2 4 6 8]
Negative indexing  7


In [8]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]  
                 ])
print("Specific element ",arr_2d[1,2])
print("Entire row ",arr_2d[1])
print("Entire column ",arr_2d[:,1])

Specific element  6
Entire row  [4 5 6]
Entire column  [2 5 8]


<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
Sorting
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [17]:
unsorted=np.array([1,3,6,4,2,4,6,8,3,1])
print("Sorted array ",np.sort(unsorted))

arr_2d_unsorted=np.array([[1,3],[7,1],[0,3]])
print(np.sort(arr_2d_unsorted,axis=0))

Sorted array  [1 1 2 3 3 4 4 6 6 8]
[[0 1]
 [1 3]
 [7 3]]


<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
Filtering
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [18]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers=numbers[numbers%2==0]
print("even numbers ",even_numbers)

even numbers  [ 2  4  6  8 10]


<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
Filtering with mask
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [22]:
mask=numbers>5
print("mask",numbers[mask])


where_result=np.where(numbers>5)
print("NP where ",numbers[where_result])

mask [ 6  7  8  9 10]
NP where  [ 6  7  8  9 10]


In [ ]:
where_result=np.where(numbers>5,numbers*2,numbers)
print("where result",where_result) # this syntax mean that if numbers are greater than 5 so multiply it other just print it

where result [ 1  2  3  4  5 12 14 16 18 20]


<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
Adding and Removing Data
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [25]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combines=np.concatenate((arr1,arr2))
print(combines)

[1 2 3 4 5 6]


In [27]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
print("Compatibility",a.shape==b.shape)

Compatibility True


<h2 style="text-align: center; font-family: Georgia, serif; letter-spacing: 3px; color: #fff; font-size: 1.6em; font-weight: 700; margin-bottom: 0;">
Hstack vs Vstack
</h2>
<hr style="border: none; height: 1px; background-color: #fff; width: 35%; margin: 6px auto;">

In [ ]:
original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])
with_new_row=np.vstack((original,new_row))# vstack always add row

new_col=np.array([[7],[9]])
with_new_col=np.hstack((original,new_col))# hstack always add column
print("new col added ",with_new_col)

new col added  [[1 2 7]
 [3 4 9]]


In [32]:
arr=np.array([1,2,3,4,5])
print("deleted array",np.delete(arr,2)) # this will delete the element at index 2   

deleted array [1 2 4 5]
